/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Session
         * @description Create a new analysis session.
         */
        post: operations["create_session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents
         * @description List all documents in a session.
         */
        get: operations["list_documents_api_v1_sessions__session_id__documents_get"];
        put?: never;
        /**
         * Upload Document
         * @description Upload a document to a session.
         */
        post: operations["upload_document_api_v1_sessions__session_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Document
         * @description Delete a specific document.
         */
        delete: operations["delete_document_api_v1_sessions__session_id__documents__doc_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger Analysis
         * @description Trigger full analysis pipeline (runs in background).
         */
        post: operations["trigger_analysis_api_v1_sessions__session_id__analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/analysis/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis Status
         * @description Poll analysis progress.
         */
        get: operations["get_analysis_status_api_v1_sessions__session_id__analysis_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analysis
         * @description Get complete analysis results.
         */
        get: operations["get_analysis_api_v1_sessions__session_id__analysis_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Market Data
         * @description Get market context data for a session.
         */
        get: operations["get_market_data_api_v1_sessions__session_id__market_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description Delete all session data (GDPR right to erasure).
         */
        delete: operations["delete_session_api_v1_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Session
         * @description Export all session data as JSON (GDPR data portability).
         */
        get: operations["export_session_api_v1_sessions__session_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResponse */
        AnalysisResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Status */
            status: string;
            property_data?: components["schemas"]["PropertyDTO"] | null;
            /**
             * Strengths
             * @default []
             */
            strengths: string[];
            /**
             * Weaknesses
             * @default []
             */
            weaknesses: string[];
            risk_score?: components["schemas"]["RiskScoreDTO"] | null;
            /** Market Position */
            market_position?: {
                [key: string]: unknown;
            } | null;
            /** Bidding Advice */
            bidding_advice?: {
                [key: string]: components["schemas"]["BiddingAdviceDTO"];
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
            /** Error Message */
            error_message?: string | null;
        };
        /** AnalysisStatusResponse */
        AnalysisStatusResponse: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Status */
            status: string;
            /** Progress Message */
            progress_message: string;
        };
        /** BiddingAdviceDTO */
        BiddingAdviceDTO: {
            /** Strategy */
            strategy: string;
            /** Min Price */
            min_price: number;
            /** Max Price */
            max_price: number;
            /** Recommended Price */
            recommended_price: number;
            /** Explanation */
            explanation: string;
        };
        /** Body_upload_document_api_v1_sessions__session_id__documents_post */
        Body_upload_document_api_v1_sessions__session_id__documents_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentUploadResponse"][];
        };
        /** DocumentUploadResponse */
        DocumentUploadResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Filename */
            filename: string;
            /** Document Type */
            document_type: string;
            /** File Size Bytes */
            file_size_bytes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MarketDataResponse */
        MarketDataResponse: {
            /** Municipality */
            municipality?: string | null;
            /** Avg Purchase Price */
            avg_purchase_price?: number | null;
            /** Num Transactions */
            num_transactions?: number | null;
            /** Price Index */
            price_index?: number | null;
            /** Period */
            period?: string | null;
            /** Bag Data */
            bag_data?: {
                [key: string]: unknown;
            } | null;
            /** Energy Label Data */
            energy_label_data?: {
                [key: string]: unknown;
            } | null;
        };
        /** PropertyDTO */
        PropertyDTO: {
            /** Address */
            address?: string | null;
            /** Postal Code */
            postal_code?: string | null;
            /** City */
            city?: string | null;
            /** Square Meters */
            square_meters?: number | null;
            /** Year Built */
            year_built?: number | null;
            /** Energy Label */
            energy_label?: string | null;
            /** Property Type */
            property_type?: string | null;
            /** Asking Price */
            asking_price?: number | null;
            /** Hoa Monthly Cost */
            hoa_monthly_cost?: number | null;
            /** Num Rooms */
            num_rooms?: number | null;
            /** Has Garden */
            has_garden?: boolean | null;
            /** Has Parking */
            has_parking?: boolean | null;
        };
        /** RiskFindingDTO */
        RiskFindingDTO: {
            /** Category */
            category: string;
            /** Severity */
            severity: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Source */
            source: string;
        };
        /** RiskScoreDTO */
        RiskScoreDTO: {
            /** Overall Score */
            overall_score: number;
            /** Risk Level */
            risk_level: string;
            /** Category Scores */
            category_scores: {
                [key: string]: number;
            };
            /** Findings */
            findings: components["schemas"]["RiskFindingDTO"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_documents_api_v1_sessions__session_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_api_v1_sessions__session_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_api_v1_sessions__session_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_document_api_v1_sessions__session_id__documents__doc_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
                doc_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_analysis_api_v1_sessions__session_id__analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_status_api_v1_sessions__session_id__analysis_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_api_v1_sessions__session_id__analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_market_data_api_v1_sessions__session_id__market_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketDataResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_session_api_v1_sessions__session_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
